name: Playwright Tests
on:
  deployment_status:
jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use pnpm instead of npm
        uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 8  # Optional: specify a pnpm version
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Check BASE_URL
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
        run: echo "URL is $BASE_URL"
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_KEN_EMAIL: ${{ secrets.PLAYWRIGHT_KEN_EMAIL }}
          PLAYWRIGHT_KEN_PASSWORD: ${{ secrets.PLAYWRIGHT_KEN_PASSWORD }}
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
